title: Andrew Melwin
email: andrewmelwinraj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
         If any of you Lack Wisdom, let him ask unto God, who gives generously to all. Welcome to My personal blog

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andrewmelwin
github_username:  andrew4cloud

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
